runtime: nodejs18
instance_class: F1

env_variables:
  MONGODB_URI: "mongodb+srv://familyitzhakov:JTCEVojOAWqRu3SN@nightscout-cluster.oxh4avh.mongodb.net/nightscout?retryWrites=true&w=majority"
  API_SECRET: "Ido18072010!"
  DISPLAY_UNITS: "mg/dl"
  LANGUAGE: "en"
  TZ: "Asia/Jerusalem"
  ENABLE: "careportal basal iob cob sage cage bwp rawbg status"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 1
